client_config_backend: settings
client_config:
  client_id: 547881618249-u11kmolhbaf7u8kf4v2nnpkps829ipmp.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install