# Generated by Django 3.2.9 on 2021-12-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_auto_20211203_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
