# Generated by Django 3.2.9 on 2022-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default=3, null=True),
        ),
    ]
