# Generated by Django 3.2.9 on 2022-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('regular_user', 'Regular User'), ('bussiness_user', 'Bussiness User')], default='regular_user', null=True),
        ),
    ]
