# Generated by Django 3.2.9 on 2022-01-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('E', 'Employee'), ('R', 'Regular User'), ('B', 'Bussiness User')], default='R', max_length=1),
        ),
    ]
