# Generated by Django 3.2.9 on 2022-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Managers'), ('EMPLOYEE', 'Employee'), ('REGULAR_USER', 'Regular User'), ('BUSSINESS_USER', 'Bussiness User'), ('TOUR_OPERATOR', 'Tour Operator')], default='REGULAR_USER', max_length=20, null=True),
        ),
    ]
