# Generated by Django 3.2.9 on 2022-04-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='checkin_date',
            field=models.DateField(null=True, verbose_name='Регистрация заезда с'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='checkout_date',
            field=models.DateField(null=True, verbose_name='Регистрация выезда до'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='food_category_abbreviation',
            field=models.CharField(default=None, max_length=2, null=True, verbose_name='Аббревиатура питания'),
        ),
    ]
