# Generated by Django 3.2.9 on 2021-12-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
