# Generated by Django 3.2.9 on 2022-04-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20220419_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подкатегории')),
            ],
        ),
        migrations.AddField(
            model_name='facilitiesandserviceshotels',
            name='category_id',
            field=models.ManyToManyField(to='booking_system.Category', verbose_name='Подкатегория'),
        ),
    ]
