# Generated by Django 3.2.9 on 2022-01-18 10:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hotel_id', chained_model_field='hotel_id', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='booking_system.room'),
        ),
    ]
