# Generated by Django 3.2.9 on 2022-04-26 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_hotelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('TENGE', 'TENGE'), ('DOLLAR', 'DOLLAR')], default='DOLLAR', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='ChildService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('until_age', models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(1)], verbose_name='С какого возраста')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('TENGE', 'TENGE'), ('DOLLAR', 'DOLLAR')], default='DOLLAR', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Услуги проживания с детьми',
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category_id',
            field=models.ManyToManyField(blank=True, to='booking_system.FacilitiesAndServicesHotels', verbose_name='Удобства и услуги'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='additional_service_id',
            field=models.ManyToManyField(blank=True, to='booking_system.AdditionalService', verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='child_service_id',
            field=models.ManyToManyField(blank=True, to='booking_system.ChildService', verbose_name='Услуги проживания с детьми'),
        ),
    ]
