# Generated by Django 3.2.9 on 2022-04-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0003_auto_20220419_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Подкатегории услуги удобств отелей'},
        ),
        migrations.RemoveField(
            model_name='facilitiesandserviceshotels',
            name='category_id',
        ),
        migrations.AddField(
            model_name='facilitiesandserviceshotels',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.category', verbose_name='Подкатегория'),
        ),
    ]
