# Generated by Django 3.2.9 on 2022-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_auto_20220419_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('TENGE', 'TENGE'), ('DOLLAR', 'DOLLAR')], default='DOLLAR', max_length=10),
        ),
    ]
