# Generated by Django 3.2.9 on 2022-04-27 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_auto_20220426_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childservice',
            name='until_age',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(17), django.core.validators.MinValueValidator(1)], verbose_name='До какого возраста'),
        ),
    ]
