# Generated by Django 3.2.9 on 2022-04-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0005_room_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='checkin_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Регистрация заезда с'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='checkout_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Регистрация выезда до'),
        ),
    ]
