# Generated by Django 3.2.9 on 2022-05-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0006_alter_hotelimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='images',
            new_name='image',
        ),
    ]
