# Generated by Django 3.2.9 on 2022-01-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0006_booking_is_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='category_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, to='booking_system.Category'),
        ),
    ]
