# Generated by Django 3.2.9 on 2022-05-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0007_rename_images_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='booking_system.hotelimage'),
        ),
    ]
