# Generated by Django 3.2.9 on 2022-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0009_auto_20220505_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
