# Generated by Django 3.2.9 on 2022-05-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0010_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
