# Generated by Django 3.2.9 on 2022-01-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0011_auto_20220124_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='food_category',
        ),
        migrations.AddField(
            model_name='hotel',
            name='food_category',
            field=models.ManyToManyField(blank=True, null=True, to='booking_system.FoodCategory'),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_category',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_category',
            field=models.ManyToManyField(blank=True, null=True, to='booking_system.HotelCategory'),
        ),
    ]
