# Generated by Django 3.2.9 on 2022-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0011_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
