# Generated by Django 3.2.9 on 2022-01-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0012_auto_20220124_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': '1. Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '6. Категории'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': '3. Страны и города'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': '5. Категории питания'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': '2. Отели'},
        ),
        migrations.AlterModelOptions(
            name='hotelcategory',
            options={'verbose_name_plural': '4. Категории отелей(звезды)'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': '7. Номера'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_id',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.room'),
        ),
    ]
