# Generated by Django 3.2.9 on 2022-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0012_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='image_url',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
