# Generated by Django 3.2.9 on 2022-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0014_alter_hotelimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50, verbose_name='Название периода')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
