# Generated by Django 3.2.9 on 2022-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0015_remove_characteristics_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='category_id',
            field=models.ManyToManyField(blank=True, default='Hotel', to='booking_system.Category'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='food_category',
            field=models.ManyToManyField(blank=True, to='booking_system.FoodCategory'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_category',
            field=models.ManyToManyField(blank=True, to='booking_system.HotelCategory'),
        ),
    ]
