# Generated by Django 3.2.9 on 2022-05-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0016_auto_20220510_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodprice',
            options={'verbose_name_plural': 'Период и цены'},
        ),
    ]
