# Generated by Django 3.2.9 on 2022-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0016_auto_20220205_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcategory',
            name='hotelcategory_stars',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
