# Generated by Django 3.2.9 on 2022-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0017_alter_periodprice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='currency',
        ),
        migrations.AddField(
            model_name='periodprice',
            name='currency',
            field=models.CharField(choices=[('EURO', 'EURO'), ('SOM', 'SOM'), ('TENGE', 'TENGE'), ('DOLLAR', 'DOLLAR')], default='DOLLAR', max_length=10),
        ),
    ]
