# Generated by Django 3.2.9 on 2022-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0018_auto_20220510_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='childservice',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='childservice',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена или проценты'),
        ),
    ]
