# Generated by Django 3.2.9 on 2022-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0019_auto_20220511_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childservice',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='Проценты'),
        ),
        migrations.AlterField(
            model_name='periodprice',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
