# Generated by Django 3.2.9 on 2022-05-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0020_auto_20220511_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.ManyToManyField(blank=True, to='booking_system.PeriodPrice', verbose_name='Цены'),
        ),
    ]
