# Generated by Django 3.2.9 on 2022-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0021_alter_hotelcategory_hotelcategory_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='foodcategory_abbreviation',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
