# Generated by Django 3.2.9 on 2022-05-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0021_alter_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_address_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_address_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(blank=True, max_length=3500, null=True, verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description_en',
            field=models.TextField(blank=True, max_length=3500, null=True, verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description_ru',
            field=models.TextField(blank=True, max_length=3500, null=True, verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название отеля'),
        ),
    ]
