# Generated by Django 3.2.9 on 2022-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0022_foodcategory_foodcategory_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesAndServicesRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '8. Удобства и услуги комнат',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='FacilitiesAndServicesHotels',
        ),
        migrations.RenameModel(
            old_name='HotelCategory',
            new_name='HotelCategoryStars',
        ),
        migrations.AlterModelOptions(
            name='facilitiesandserviceshotels',
            options={'verbose_name_plural': '6. Удобства и услуги отелей'},
        ),
        migrations.RenameField(
            model_name='facilitiesandserviceshotels',
            old_name='category_name',
            new_name='hotel_category_name',
        ),
        migrations.AddField(
            model_name='room',
            name='category_id',
            field=models.ManyToManyField(blank=True, default='Hotel', to='booking_system.FacilitiesAndServicesHotels'),
        ),
    ]
