# Generated by Django 3.2.9 on 2022-02-05 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_system', '0023_auto_20220205_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID гостя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_system.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_checkout',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_of_guest',
            field=models.IntegerField(default=1, verbose_name='Кол-во гостей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hotel', chained_model_field='hotel_id', on_delete=django.db.models.deletion.CASCADE, to='booking_system.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='capacity',
            field=models.IntegerField(default=1, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=50, verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Почтовый код'),
        ),
        migrations.AlterField(
            model_name='country',
            name='contry_name',
            field=models.CharField(max_length=50, verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='facilitiesandserviceshotels',
            name='hotel_category_name',
            field=models.CharField(max_length=50, verbose_name='Наименование услуги и удобств отеля'),
        ),
        migrations.AlterField(
            model_name='facilitiesandservicesrooms',
            name='room_category_name',
            field=models.CharField(max_length=50, verbose_name='Наименование услуги и удобств комнаты'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='foodcategory_abbreviation',
            field=models.CharField(default=None, max_length=2, verbose_name='Аббревиатура питания'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='foodcategory_name',
            field=models.CharField(max_length=50, verbose_name='Категория питания'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category_id',
            field=models.ManyToManyField(blank=True, default='Hotel', to='booking_system.FacilitiesAndServicesHotels', verbose_name='Удобства и услуги'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='food_category',
            field=models.ManyToManyField(blank=True, to='booking_system.FoodCategory', verbose_name='Категории питания'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_category',
            field=models.ManyToManyField(blank=True, to='booking_system.HotelCategoryStars', verbose_name='Звезды отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='hotelcategorystars',
            name='hotelcategory_name',
            field=models.CharField(max_length=50, verbose_name='Категория звезд отеля'),
        ),
        migrations.AlterField(
            model_name='hotelcategorystars',
            name='hotelcategory_stars',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Звезды'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category_id',
            field=models.ManyToManyField(blank=True, default='Hotel', to='booking_system.FacilitiesAndServicesRooms', verbose_name='Удобства и услуги комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Забронирован'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(blank=True, default=1000.0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(blank=True, default=101, null=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
