# Generated by Django 3.2.9 on 2022-05-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0024_auto_20220518_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodprice',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='booking_system.room', verbose_name='Комната'),
        ),
    ]
