# Generated by Django 3.2.9 on 2022-02-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0025_alter_hotel_hotel_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': '7. Типы Номеров'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='characteristics',
            name='hotel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.hotel', verbose_name='Отель'),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
