# Generated by Django 3.2.9 on 2022-02-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0026_auto_20220223_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='hotel_id',
        ),
    ]
