# Generated by Django 3.2.9 on 2022-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0028_auto_20220223_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='characteristics_id',
            field=models.ManyToManyField(blank=True, null=True, to='booking_system.Characteristics', verbose_name='Комната'),
        ),
    ]
