# Generated by Django 3.2.9 on 2022-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0029_auto_20220223_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_id',
            field=models.ManyToManyField(blank=True, null=True, to='booking_system.Room', verbose_name='Типы комнат'),
        ),
    ]
