# Generated by Django 3.2.9 on 2022-02-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0030_auto_20220223_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristics',
            options={'verbose_name_plural': '7. Характеристики'},
        ),
    ]
