# Generated by Django 3.2.9 on 2022-05-23 07:55

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0031_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='hotel', chained_model_field='hotel', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.room', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='periodprice',
            name='price',
            field=models.FloatField(default=0, null=True, verbose_name='Цена'),
        ),
    ]
