# Generated by Django 3.2.9 on 2022-05-23 07:58

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0033_auto_20220523_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='room', chained_model_field='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_system.room', verbose_name='Номер'),
        ),
    ]
