# Generated by Django 3.2.9 on 2022-05-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0035_auto_20220523_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='booking_system.hotel', verbose_name='Отель'),
        ),
    ]
