# Generated by Django 3.2.9 on 2022-05-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0038_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
    ]
