# Generated by Django 3.2.9 on 2022-05-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0039_remove_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='booking_system.hotel'),
        ),
    ]
