# Generated by Django 3.2.9 on 2022-05-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0041_auto_20220523_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodprice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('KGS', 'KGS'), ('KZT', 'KZT'), ('USD', 'USD')], default='USD', max_length=10),
        ),
    ]
