# Generated by Django 3.2.9 on 2022-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0042_alter_periodprice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('KGS', 'KGS'), ('KZT', 'KZT'), ('USD', 'USD')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='childservice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('KGS', 'KGS'), ('KZT', 'KZT'), ('USD', 'USD')], default='USD', max_length=10),
        ),
    ]
