# Generated by Django 3.2.9 on 2022-06-05 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0044_auto_20220602_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='characteristics',
            options={'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Страны и города'},
        ),
        migrations.AlterModelOptions(
            name='facilitiesandserviceshotels',
            options={'verbose_name_plural': 'Удобства и услуги отелей'},
        ),
        migrations.AlterModelOptions(
            name='facilitiesandservicesrooms',
            options={'verbose_name_plural': 'Удобства и услуги комнат'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'Категории питания'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='hotelcategorystars',
            options={'verbose_name_plural': 'Категории отелей(звезды)'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Типы Номеров'},
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{8,15}$')]),
        ),
    ]
