# Generated by Django 3.2.9 on 2022-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0045_auto_20220605_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Подкатегории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Подкатегории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Подкатегории'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='childservice',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='childservice',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='childservice',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='facilitiesandserviceshotels',
            name='hotel_category_name',
            field=models.CharField(max_length=100, verbose_name='Наименование услуги и удобств отеля'),
        ),
        migrations.AlterField(
            model_name='facilitiesandserviceshotels',
            name='hotel_category_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование услуги и удобств отеля'),
        ),
        migrations.AlterField(
            model_name='facilitiesandserviceshotels',
            name='hotel_category_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование услуги и удобств отеля'),
        ),
        migrations.AlterField(
            model_name='facilitiesandservicesrooms',
            name='room_category_name',
            field=models.CharField(max_length=100, verbose_name='Наименование услуги и удобств комнаты'),
        ),
        migrations.AlterField(
            model_name='facilitiesandservicesrooms',
            name='room_category_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование услуги и удобств комнаты'),
        ),
        migrations.AlterField(
            model_name='facilitiesandservicesrooms',
            name='room_category_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование услуги и удобств комнаты'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='food_category_name',
            field=models.CharField(max_length=100, verbose_name='Категория питания'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='food_category_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория питания'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='food_category_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория питания'),
        ),
    ]
