# Generated by Django 3.2.9 on 2022-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0046_auto_20220607_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(blank=True, to='booking_system.Room', verbose_name='Номер'),
        ),
    ]
