# Generated by Django 3.2.9 on 2022-06-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0047_alter_booking_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='category_id',
            new_name='facilities_hotel_id',
        ),
        migrations.RemoveField(
            model_name='facilitiesandserviceshotels',
            name='category_id',
        ),
    ]
