# Generated by Django 3.2.9 on 2022-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0050_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
