# Generated by Django 3.2.9 on 2022-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0057_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
